services:
  petatdb:
    image: mongo:latest
    container_name: petatdb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - petatdb-data:/data/db

volumes:
  petatdb-data: